spring.application.name=service-discovery
server.port=8761

#Configuración del servidor Eureka
#El servidor no se registra a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# URL del servidor Eureka
eureka.client.service-url.defaultZone=http://service-discovery:8761/eureka/

# Tiempo de espera para que los clientes envíen signos de vida
eureka.server.wait-time-in-ms-when-sync-empty=0

# Configuración adicional
logging.level.com.netflix.eureka=DEBUG
logging.level.com.netflix.discovery=DEBUG

# Configuración de seguridad
spring.security.user.name=eureka
spring.security.user.password=eureka2026

# Eliminar registros vencidos más rápido
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Expirar instancias muertas más pronto
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always