server.port=8090

# Información de aplicación (para endpoint /actuator/info)
info.app.name=msBanco
info.app.description=Microservicio para operaciones bancarias
info.app.version=1.0.0

# Configuracion de conexion a base de datos
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/backend_3
spring.datasource.username=myuser
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JWT de servicio (compartido con BFF)
jwt.service-secret=Clave-secreta-Bff-Servicio-F4hJ1cG0sZ8eN4wM7uO9iT2aB5kL3dP6jH8rX1

# Configuración de Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreaker.enabled=true

# Credenciales de Spring Security (sobreescriben las del microservicio)
spring.security.user.name=user
spring.security.user.password=password

# Eureka
eureka.client.service-url.defaultZone=http://eureka:eureka2026@service-discovery:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.healthcheck.enabled=true

# Resilience4j (Circuit Breaker)
resilience4j.circuitbreaker.instances.bancoBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.bancoBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.bancoBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.bancoBreaker.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.bancoBreaker.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.bancoBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.bancoBreaker.automaticTransitionFromOpenToHalfOpenEnabled=true

# Configuración de ActiveMQ
spring.activemq.broker-url=http://activemq:61616
spring.activemq.user=admin
spring.activemq.password=password

# Seguridad con OAuth2 y JWT (URL para validar tokens JWT emitidos por el Authorization Server)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-server:8080/.well-known/jwks.json